run:
  timeout: 5m
  skip-files: []

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 16
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/pkg/errors
  godox:
    keywords:
      - FIXME
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
  forbidigo:
    forbid:
      - '^print(ln)?$'
#      - '^fmt\.Print(f|ln)?$'
#      - '^panic$'
      - '^spew\.Print(f|ln)?$'
      - '^spew\.Dump$'
  gomoddirectives:
    replace-local: false
    replace-allow-list:
      - github.com/abbot/go-http-auth
      - github.com/go-check/check
      - github.com/gorilla/mux
      - github.com/mailgun/minheap
      - github.com/mailgun/multibuf
      - github.com/docker/docker
  funlen:
    lines: 120 # default 60
    statements: 50 # default 40

linters:
  enable-all: true
  disable:
    - bodyclose # Too many false-positive and panics.
    - cyclop # Duplicate of gocyclo
    - dupl # Too strict
    - exhaustive # Not relevant
    - exhaustivestruct # Not relevant
    - forcetypeassert # Too strict
    - gochecknoglobals
    - gochecknoinits
    - gocognit # Too strict
    - gocyclo # FIXME must be fixed
    - godox # Too strict
    - goerr113 # Too strict
    - golint # Deprecated
    - gomnd # Too strict
    - gosec # Too strict
    - ifshort # Not relevant
    - interfacer # Deprecated
    - lll # Not relevant
    - makezero # Not relevant
    - maligned # Deprecated
    - nestif # Too many false-positive.
    - nlreturn # Not relevant
    - noctx # Too strict
    - paralleltest # Not relevant
    - prealloc # Too many false-positive.
    - rowserrcheck # Not relevant (SQL)
    - scopelint # Deprecated
    - sqlclosecheck # Not relevant (SQL)
    - stylecheck # skip because report issues related to some generated files.
    - tagliatelle # Not compatible with current tags.
    - testpackage # Too strict
    - tparallel # Not relevant
    - unparam # Too strict
    - wrapcheck # Too strict
    - wsl # Too strict

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'exported: exported type (.+) should have comment or be unexported'
  exclude-rules:
    - path: annotations.go
      text: (compatibilityMapping) is a global variable
    - path: .*_test.go
      text: (updateExpected) is a global variable
    - path: .*_test.go
      linters:
        - varnamelen
    - path: main.go
      text: (Version|ShortCommit|Date) is a global variable
    - path: main.go
      text: exported var (Version|ShortCommit|Date) should have comment or be unexported
    - path: ingress/annotations.go
      text: '`getBoolValue` - `defaultValue` always receives `false`'
    - path: static/v1.go
      text: exported type `(.+)` should have comment or be unexported
    - path: acme/acme.go
      text: Error return value of `(.+).Encode` is not checked
    - path: ingress/parser.go
      text: parseYaml returns interface (.+)
